# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CLIC 2014
tagline:          'December 10, 2014 · UVSQ'
description:      'Codes, Lattices, Ideals, Cryptography.'
url:              http://idealcodes.github.io/clic-2014
baseurl:          /clic-2014

author:
  name:           'Idealcodes'
  url:            https://idealcodes.github.io/

collections:
  abstracts:
    permalink: /abstract/:path.html
  
#paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/idealcodes/clic-2014
